[plugin]
repository = "https://github.com/RaylaValdez/SimonSays.git"
commit = "47972d815c4d7501e5037fcbe946296da6ef0a77"
owners = ["RaylaValdez"]
project_path = "SimonSays"
changelog = "Testing Release"