[plugin]
repository = "https://github.com/RaylaValdez/SimonSays.git"
commit = "fd6ac397bc6dd400cc5cceb168c6153a5f2b65e3"
owners = ["RaylaValdez"]
project_path = "SimonSays"
changelog = "Testing Release"